main:
  - name: 关于我
    url: '#about'
    weight: 1
  - name: 博文
    url: /posts/
    weight: 2
  - name: 文档
    url: /docs/
    weight: 3
  - name: 标签
    url: /tags/
    weight: 4
  - name: 归档
    url: /categories/
    weight: 5